-- 담당자 7 · F-OPS-005/006 · CHG 번호는 정본 담당 승인 후 부여
-- TRADE_DISPUTE 관리자 판정 컬럼/공통코드 공용 DB 적용 전 읽기 전용 진단
-- 이 파일은 데이터를 변경하지 않는다. NCTDB에서 먼저 실행하고 결과를 보관한다.

USE NCTDB;

SELECT DATABASE() AS current_database,
       @@hostname AS server_hostname,
       @@port AS server_port,
       CURRENT_USER() AS authenticated_account,
       VERSION() AS mysql_version;

SELECT TABLE_NAME, ENGINE, TABLE_COLLATION
FROM information_schema.TABLES
WHERE TABLE_SCHEMA = DATABASE()
  AND TABLE_NAME IN ('TRADE_DISPUTE', 'TRADE_STATUS_HIST', 'TRADE', 'USERS', 'CMM_CODE')
ORDER BY TABLE_NAME;

SELECT COLUMN_NAME, COLUMN_TYPE, IS_NULLABLE, COLUMN_DEFAULT, COLUMN_COMMENT
FROM information_schema.COLUMNS
WHERE TABLE_SCHEMA = DATABASE()
  AND TABLE_NAME = 'TRADE_DISPUTE'
  AND COLUMN_NAME IN (
      'TRD_DSP_RSLT_CD',
      'TRD_DSP_PROC_RSN_CN',
      'TRD_DSP_PROC_USR_SN',
      'TRD_DSP_PROC_DT',
      'TRD_DSP_PREV_TRD_STATUS_CD'
  )
ORDER BY ORDINAL_POSITION;

SELECT child.CMM_CD,
       child.CMM_NM,
       parent.CMM_CD AS parent_code,
       child.CMM_SORT_NO,
       child.CMM_USE_YN
FROM CMM_CODE child
LEFT JOIN CMM_CODE parent ON parent.CMM_SN = child.CMM_PARENT_SN
WHERE child.CMM_CD IN (
    'TRDG06', 'TRDC0021', 'TRDC0022', 'TRDC0023', 'TRDC0024', 'STLC0004'
)
ORDER BY child.CMM_CD;

SELECT COUNT(*) AS total_dispute_count
FROM TRADE_DISPUTE;

-- 접수 시각보다 엄격히 이전인 상태이력 중 가장 최신 1건이 있을 때만 보정 후보로 본다.
WITH ranked_history AS (
    SELECT d.TRD_DSP_SN,
           h.TRD_STS_HST_STATUS_CD,
           ROW_NUMBER() OVER (
               PARTITION BY d.TRD_DSP_SN
               ORDER BY h.TRD_STS_HST_REG_DT DESC, h.TRD_STS_HST_SN DESC
           ) AS rn
    FROM TRADE_DISPUTE d
    JOIN TRADE_STATUS_HIST h
      ON h.TRD_SN = d.TRD_SN
     AND h.TRD_STS_HST_REG_DT < d.TRD_DSP_REG_DT
)
SELECT COUNT(*) AS determinable_previous_status_count
FROM ranked_history latest
JOIN CMM_CODE status_code
  ON status_code.CMM_CD = latest.TRD_STS_HST_STATUS_CD
JOIN CMM_CODE status_group
  ON status_group.CMM_SN = status_code.CMM_PARENT_SN
 AND status_group.CMM_CD = 'TRDG02'
WHERE latest.rn = 1
  AND latest.TRD_STS_HST_STATUS_CD IN ('TRDC0003', 'TRDC0004', 'TRDC0005');

SHOW CREATE TABLE TRADE_DISPUTE;

SELECT COLUMN_NAME, COLUMN_TYPE, IS_NULLABLE
FROM information_schema.COLUMNS
WHERE TABLE_SCHEMA = DATABASE()
  AND TABLE_NAME = 'TRADE_DISPUTE'
  AND COLUMN_NAME IN (
    'TRD_DSP_RSLT_CD',
    'TRD_DSP_PROC_RSN_CN',
    'TRD_DSP_PROC_USR_SN',
    'TRD_DSP_PROC_DT',
    'TRD_DSP_PREV_TRD_STATUS_CD'
  );

SELECT
    child.CMM_CD,
    child.CMM_NM,
    child.CMM_EXPLN,
    parent.CMM_CD AS PARENT_CD,
    child.CMM_SORT_NO,
    child.CMM_USE_YN
FROM CMM_CODE child
LEFT JOIN CMM_CODE parent
    ON parent.CMM_SN = child.CMM_PARENT_SN
WHERE child.CMM_CD IN (
    'TRDG06',
    'TRDC0021',
    'TRDC0022',
    'TRDC0023',
    'TRDC0024',
    'STLC0004'
)
ORDER BY child.CMM_CD;

SELECT
    k.CONSTRAINT_NAME,
    k.COLUMN_NAME,
    k.REFERENCED_TABLE_SCHEMA,
    k.REFERENCED_TABLE_NAME,
    k.REFERENCED_COLUMN_NAME,
    r.DELETE_RULE,
    r.UPDATE_RULE
FROM information_schema.KEY_COLUMN_USAGE k
JOIN information_schema.REFERENTIAL_CONSTRAINTS r
  ON r.CONSTRAINT_SCHEMA = k.CONSTRAINT_SCHEMA
 AND r.TABLE_NAME = k.TABLE_NAME
 AND r.CONSTRAINT_NAME = k.CONSTRAINT_NAME
WHERE k.CONSTRAINT_SCHEMA = DATABASE()
  AND k.TABLE_NAME = 'TRADE_DISPUTE'
  AND k.CONSTRAINT_NAME IN (
    'FK_TRADE_DISPUTE_RESULT_CODE',
    'FK_TRADE_DISPUTE_PROCESSOR',
    'FK_TRADE_DISPUTE_PREV_STATUS_CODE'
  )
ORDER BY k.CONSTRAINT_NAME;

SELECT
    SUM(
        CASE WHEN d.TRD_DSP_RSLT_CD IS NOT NULL
                  AND result_code.CMM_CD IS NULL
             THEN 1 ELSE 0 END
    ) AS INVALID_RESULT_COUNT,
    SUM(
        CASE WHEN d.TRD_DSP_PREV_TRD_STATUS_CD IS NOT NULL
                  AND prev_code.CMM_CD IS NULL
             THEN 1 ELSE 0 END
    ) AS INVALID_PREV_STATUS_COUNT
FROM TRADE_DISPUTE d
LEFT JOIN CMM_CODE result_code
  ON result_code.CMM_CD = d.TRD_DSP_RSLT_CD
LEFT JOIN CMM_CODE prev_code
  ON prev_code.CMM_CD = d.TRD_DSP_PREV_TRD_STATUS_CD;

ALTER TABLE TRADE_DISPUTE
    ADD CONSTRAINT FK_TRADE_DISPUTE_RESULT_CODE
        FOREIGN KEY (TRD_DSP_RSLT_CD)
        REFERENCES CMM_CODE (CMM_CD)
        ON DELETE RESTRICT
        ON UPDATE RESTRICT,
    ADD CONSTRAINT FK_TRADE_DISPUTE_PREV_STATUS_CODE
        FOREIGN KEY (TRD_DSP_PREV_TRD_STATUS_CD)
        REFERENCES CMM_CODE (CMM_CD)
        ON DELETE RESTRICT
        ON UPDATE RESTRICT;