-- 담당자 7 · F-OPS-005/006 · CHG 번호는 정본 담당 승인 후 부여
-- TRADE_DISPUTE 관리자 판정 컬럼, TRDG06/TRDC0021~0024, STLC0004 증분 적용
-- MySQL 8 / NCTDB 전용. 01_precheck.sql 결과 검토 및 적용 승인 후에만 실행한다.
-- 재실행 시 이미 올바르게 반영된 항목은 건너뛰고, 계약이 다른 기존 항목은 즉시 중단한다.
-- 실행 전 같은 세션에서 다음 승인 표식을 직접 설정해야 한다.
-- SET @F_OPS_005_006_SHARED_DB_APPROVED = 'APPROVED_SHARED_NCTDB';

SET @F_OPS_005_006_SHARED_DB_APPROVED = 'APPROVED_SHARED_NCTDB';

USE NCTDB;

DELIMITER $$

DROP PROCEDURE IF EXISTS SP_F_OPS_005_006_APPLY_DISPUTE_DB $$

CREATE PROCEDURE SP_F_OPS_005_006_APPLY_DISPUTE_DB()
BEGIN
    DECLARE v_count INT DEFAULT 0;
    DECLARE v_parent_sn BIGINT DEFAULT NULL;
    DECLARE v_backfilled_count INT DEFAULT 0;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
        ROLLBACK;
        RESIGNAL;
    END;

    IF COALESCE(@F_OPS_005_006_SHARED_DB_APPROVED, '') <> 'APPROVED_SHARED_NCTDB' THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'F-OPS-005/006 중단: 공용 DB 적용 승인 표식이 없습니다.';
    END IF;

    IF DATABASE() <> 'NCTDB' THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'F-OPS-005/006 중단: NCTDB에서만 실행할 수 있습니다.';
    END IF;

    SELECT COUNT(*) INTO v_count
    FROM information_schema.TABLES
    WHERE TABLE_SCHEMA = DATABASE()
      AND TABLE_NAME IN ('TRADE_DISPUTE', 'TRADE_STATUS_HIST', 'TRADE', 'USERS', 'CMM_CODE');

    IF v_count <> 5 THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'F-OPS-005/006 중단: 필수 테이블 5개를 모두 찾지 못했습니다.';
    END IF;

    -- 기존 컬럼이 있으면 타입과 NULL 계약이 정확히 일치해야 한다.
    SELECT COUNT(*) INTO v_count
    FROM information_schema.COLUMNS
    WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'TRADE_DISPUTE'
      AND COLUMN_NAME = 'TRD_DSP_RSLT_CD';
    IF v_count = 1 AND NOT EXISTS (
        SELECT 1 FROM information_schema.COLUMNS
        WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'TRADE_DISPUTE'
          AND COLUMN_NAME = 'TRD_DSP_RSLT_CD' AND COLUMN_TYPE = 'varchar(30)' AND IS_NULLABLE = 'YES'
    ) THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'F-OPS-005/006 중단: TRD_DSP_RSLT_CD 기존 계약이 다릅니다.';
    END IF;

    SELECT COUNT(*) INTO v_count
    FROM information_schema.COLUMNS
    WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'TRADE_DISPUTE'
      AND COLUMN_NAME = 'TRD_DSP_PROC_RSN_CN';
    IF v_count = 1 AND NOT EXISTS (
        SELECT 1 FROM information_schema.COLUMNS
        WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'TRADE_DISPUTE'
          AND COLUMN_NAME = 'TRD_DSP_PROC_RSN_CN' AND COLUMN_TYPE = 'varchar(4000)' AND IS_NULLABLE = 'YES'
    ) THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'F-OPS-005/006 중단: TRD_DSP_PROC_RSN_CN 기존 계약이 다릅니다.';
    END IF;

    SELECT COUNT(*) INTO v_count
    FROM information_schema.COLUMNS
    WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'TRADE_DISPUTE'
      AND COLUMN_NAME = 'TRD_DSP_PROC_USR_SN';
    IF v_count = 1 AND NOT EXISTS (
        SELECT 1 FROM information_schema.COLUMNS
        WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'TRADE_DISPUTE'
          AND COLUMN_NAME = 'TRD_DSP_PROC_USR_SN' AND COLUMN_TYPE = 'bigint' AND IS_NULLABLE = 'YES'
    ) THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'F-OPS-005/006 중단: TRD_DSP_PROC_USR_SN 기존 계약이 다릅니다.';
    END IF;

    SELECT COUNT(*) INTO v_count
    FROM information_schema.COLUMNS
    WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'TRADE_DISPUTE'
      AND COLUMN_NAME = 'TRD_DSP_PROC_DT';
    IF v_count = 1 AND NOT EXISTS (
        SELECT 1 FROM information_schema.COLUMNS
        WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'TRADE_DISPUTE'
          AND COLUMN_NAME = 'TRD_DSP_PROC_DT' AND COLUMN_TYPE = 'datetime' AND IS_NULLABLE = 'YES'
    ) THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'F-OPS-005/006 중단: TRD_DSP_PROC_DT 기존 계약이 다릅니다.';
    END IF;

    SELECT COUNT(*) INTO v_count
    FROM information_schema.COLUMNS
    WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'TRADE_DISPUTE'
      AND COLUMN_NAME = 'TRD_DSP_PREV_TRD_STATUS_CD';
    IF v_count = 1 AND NOT EXISTS (
        SELECT 1 FROM information_schema.COLUMNS
        WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'TRADE_DISPUTE'
          AND COLUMN_NAME = 'TRD_DSP_PREV_TRD_STATUS_CD' AND COLUMN_TYPE = 'varchar(30)' AND IS_NULLABLE = 'YES'
    ) THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'F-OPS-005/006 중단: TRD_DSP_PREV_TRD_STATUS_CD 기존 계약이 다릅니다.';
    END IF;

    -- 상위 그룹은 기존 정본 코드여야 한다.
    IF NOT EXISTS (SELECT 1 FROM CMM_CODE WHERE CMM_CD = 'TRDG02' AND CMM_PARENT_SN IS NULL) THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'F-OPS-005/006 중단: 거래 상태 그룹 TRDG02가 없습니다.';
    END IF;
    IF NOT EXISTS (SELECT 1 FROM CMM_CODE WHERE CMM_CD = 'STLG01' AND CMM_PARENT_SN IS NULL) THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'F-OPS-005/006 중단: 정산 상태 그룹 STLG01이 없습니다.';
    END IF;

    -- 동일 코드가 다른 의미·그룹·정렬·활성 상태로 이미 존재하면 덮어쓰지 않는다.
    IF EXISTS (
        SELECT 1 FROM CMM_CODE WHERE CMM_CD = 'TRDG06'
    ) AND NOT EXISTS (
        SELECT 1 FROM CMM_CODE
        WHERE CMM_CD = 'TRDG06'
          AND CMM_PARENT_SN IS NULL
          AND CMM_NM = '거래 문제 판정 결과'
          AND CMM_SORT_NO = 420
          AND CMM_USE_YN = 'Y'
    ) THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'F-OPS-005/006 중단: 기존 TRDG06 계약이 충돌합니다.';
    END IF;

    IF EXISTS (SELECT 1 FROM CMM_CODE WHERE CMM_CD = 'TRDC0021') AND NOT EXISTS (
        SELECT 1 FROM CMM_CODE c JOIN CMM_CODE p ON p.CMM_SN = c.CMM_PARENT_SN
        WHERE c.CMM_CD = 'TRDC0021' AND p.CMM_CD = 'TRDG06'
          AND c.CMM_NM = '처리 완료'
          AND c.CMM_SORT_NO = 10 AND c.CMM_USE_YN = 'Y'
    ) THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'F-OPS-005/006 중단: 기존 TRDC0021 계약이 충돌합니다.';
    END IF;

    IF EXISTS (SELECT 1 FROM CMM_CODE WHERE CMM_CD = 'TRDC0022') AND NOT EXISTS (
        SELECT 1 FROM CMM_CODE c JOIN CMM_CODE p ON p.CMM_SN = c.CMM_PARENT_SN
        WHERE c.CMM_CD = 'TRDC0022' AND p.CMM_CD = 'TRDG06'
          AND c.CMM_NM = '전액 환불'
          AND c.CMM_SORT_NO = 20 AND c.CMM_USE_YN = 'Y'
    ) THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'F-OPS-005/006 중단: 기존 TRDC0022 계약이 충돌합니다.';
    END IF;

    IF EXISTS (SELECT 1 FROM CMM_CODE WHERE CMM_CD = 'TRDC0023') AND NOT EXISTS (
        SELECT 1 FROM CMM_CODE c JOIN CMM_CODE p ON p.CMM_SN = c.CMM_PARENT_SN
        WHERE c.CMM_CD = 'TRDC0023' AND p.CMM_CD = 'TRDG06'
          AND c.CMM_NM = '정산 보류'
          AND c.CMM_SORT_NO = 30 AND c.CMM_USE_YN = 'Y'
    ) THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'F-OPS-005/006 중단: 기존 TRDC0023 계약이 충돌합니다.';
    END IF;

    IF EXISTS (SELECT 1 FROM CMM_CODE WHERE CMM_CD = 'TRDC0024') AND NOT EXISTS (
        SELECT 1 FROM CMM_CODE c JOIN CMM_CODE p ON p.CMM_SN = c.CMM_PARENT_SN
        WHERE c.CMM_CD = 'TRDC0024' AND p.CMM_CD = 'TRDG06'
          AND c.CMM_NM = '관리자 종결'
          AND c.CMM_SORT_NO = 40 AND c.CMM_USE_YN = 'N'
    ) THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'F-OPS-005/006 중단: 기존 TRDC0024 계약이 충돌합니다.';
    END IF;

    IF EXISTS (SELECT 1 FROM CMM_CODE WHERE CMM_CD = 'STLC0004') AND NOT EXISTS (
        SELECT 1 FROM CMM_CODE c JOIN CMM_CODE p ON p.CMM_SN = c.CMM_PARENT_SN
        WHERE c.CMM_CD = 'STLC0004' AND p.CMM_CD = 'STLG01'
          AND c.CMM_NM = '환불종결'
          AND c.CMM_SORT_NO = 40 AND c.CMM_USE_YN = 'Y'
    ) THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'F-OPS-005/006 중단: 기존 STLC0004 계약이 충돌합니다.';
    END IF;

    -- 부분 적용 재실행 시 동명 인덱스/FK가 다른 정의면 첫 쓰기 전에 중단한다.
    IF EXISTS (
        SELECT 1 FROM information_schema.STATISTICS
        WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'TRADE_DISPUTE'
          AND INDEX_NAME = 'IDX_TRADE_DISPUTE_RESULT'
    ) AND NOT (
        (SELECT COUNT(*) FROM information_schema.STATISTICS
         WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'TRADE_DISPUTE'
           AND INDEX_NAME = 'IDX_TRADE_DISPUTE_RESULT') = 1
        AND EXISTS (
            SELECT 1 FROM information_schema.STATISTICS
            WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'TRADE_DISPUTE'
              AND INDEX_NAME = 'IDX_TRADE_DISPUTE_RESULT'
              AND SEQ_IN_INDEX = 1 AND COLUMN_NAME = 'TRD_DSP_RSLT_CD'
        )
    ) THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'F-OPS-005/006 중단: IDX_TRADE_DISPUTE_RESULT 정의가 다릅니다.';
    END IF;

    IF EXISTS (
        SELECT 1 FROM information_schema.STATISTICS
        WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'TRADE_DISPUTE'
          AND INDEX_NAME = 'IDX_TRADE_DISPUTE_PROC_USR'
    ) AND NOT (
        (SELECT COUNT(*) FROM information_schema.STATISTICS
         WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'TRADE_DISPUTE'
           AND INDEX_NAME = 'IDX_TRADE_DISPUTE_PROC_USR') = 1
        AND EXISTS (
            SELECT 1 FROM information_schema.STATISTICS
            WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'TRADE_DISPUTE'
              AND INDEX_NAME = 'IDX_TRADE_DISPUTE_PROC_USR'
              AND SEQ_IN_INDEX = 1 AND COLUMN_NAME = 'TRD_DSP_PROC_USR_SN'
        )
    ) THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'F-OPS-005/006 중단: IDX_TRADE_DISPUTE_PROC_USR 정의가 다릅니다.';
    END IF;

    IF EXISTS (
        SELECT 1 FROM information_schema.STATISTICS
        WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'TRADE_DISPUTE'
          AND INDEX_NAME = 'IDX_TRADE_DISPUTE_PREV_STATUS'
    ) AND NOT (
        (SELECT COUNT(*) FROM information_schema.STATISTICS
         WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'TRADE_DISPUTE'
           AND INDEX_NAME = 'IDX_TRADE_DISPUTE_PREV_STATUS') = 1
        AND EXISTS (
            SELECT 1 FROM information_schema.STATISTICS
            WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'TRADE_DISPUTE'
              AND INDEX_NAME = 'IDX_TRADE_DISPUTE_PREV_STATUS'
              AND SEQ_IN_INDEX = 1 AND COLUMN_NAME = 'TRD_DSP_PREV_TRD_STATUS_CD'
        )
    ) THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'F-OPS-005/006 중단: IDX_TRADE_DISPUTE_PREV_STATUS 정의가 다릅니다.';
    END IF;

    -- 이전 수동 보정 과정에서 기존 FK와 같은 FK가 정본 이름으로 중복 추가된 경우만 제거한다.
    -- 두 제약이 모두 단일 컬럼·동일 대상·제한 규칙일 때만 새로 추가된 쪽을 제거한다.
    IF EXISTS (
        SELECT 1
        FROM information_schema.KEY_COLUMN_USAGE k
        JOIN information_schema.REFERENTIAL_CONSTRAINTS r
          ON r.CONSTRAINT_SCHEMA = k.CONSTRAINT_SCHEMA
         AND r.CONSTRAINT_NAME = k.CONSTRAINT_NAME
         AND r.TABLE_NAME = k.TABLE_NAME
        WHERE k.CONSTRAINT_SCHEMA = DATABASE() AND k.TABLE_NAME = 'TRADE_DISPUTE'
          AND k.CONSTRAINT_NAME = 'FK_TRADE_DISPUTE_RESULT_CODE'
          AND k.COLUMN_NAME = 'TRD_DSP_RSLT_CD'
          AND k.REFERENCED_TABLE_SCHEMA = DATABASE()
          AND k.REFERENCED_TABLE_NAME = 'CMM_CODE' AND k.REFERENCED_COLUMN_NAME = 'CMM_CD'
          AND r.DELETE_RULE IN ('RESTRICT', 'NO ACTION')
          AND r.UPDATE_RULE IN ('RESTRICT', 'NO ACTION')
          AND (SELECT COUNT(*) FROM information_schema.KEY_COLUMN_USAGE k2
               WHERE k2.CONSTRAINT_SCHEMA = k.CONSTRAINT_SCHEMA
                 AND k2.TABLE_NAME = k.TABLE_NAME
                 AND k2.CONSTRAINT_NAME = k.CONSTRAINT_NAME) = 1
    ) AND EXISTS (
        SELECT 1
        FROM information_schema.KEY_COLUMN_USAGE k
        JOIN information_schema.REFERENTIAL_CONSTRAINTS r
          ON r.CONSTRAINT_SCHEMA = k.CONSTRAINT_SCHEMA
         AND r.CONSTRAINT_NAME = k.CONSTRAINT_NAME
         AND r.TABLE_NAME = k.TABLE_NAME
        WHERE k.CONSTRAINT_SCHEMA = DATABASE() AND k.TABLE_NAME = 'TRADE_DISPUTE'
          AND k.CONSTRAINT_NAME = 'FK_TRADE_DISPUTE_RESULT_CD'
          AND k.COLUMN_NAME = 'TRD_DSP_RSLT_CD'
          AND k.REFERENCED_TABLE_SCHEMA = DATABASE()
          AND k.REFERENCED_TABLE_NAME = 'CMM_CODE' AND k.REFERENCED_COLUMN_NAME = 'CMM_CD'
          AND r.DELETE_RULE IN ('RESTRICT', 'NO ACTION')
          AND r.UPDATE_RULE IN ('RESTRICT', 'NO ACTION')
          AND (SELECT COUNT(*) FROM information_schema.KEY_COLUMN_USAGE k2
               WHERE k2.CONSTRAINT_SCHEMA = k.CONSTRAINT_SCHEMA
                 AND k2.TABLE_NAME = k.TABLE_NAME
                 AND k2.CONSTRAINT_NAME = k.CONSTRAINT_NAME) = 1
    ) THEN
        ALTER TABLE TRADE_DISPUTE
            DROP FOREIGN KEY FK_TRADE_DISPUTE_RESULT_CODE;
    END IF;

    IF EXISTS (
        SELECT 1
        FROM information_schema.KEY_COLUMN_USAGE k
        JOIN information_schema.REFERENTIAL_CONSTRAINTS r
          ON r.CONSTRAINT_SCHEMA = k.CONSTRAINT_SCHEMA
         AND r.CONSTRAINT_NAME = k.CONSTRAINT_NAME
         AND r.TABLE_NAME = k.TABLE_NAME
        WHERE k.CONSTRAINT_SCHEMA = DATABASE() AND k.TABLE_NAME = 'TRADE_DISPUTE'
          AND k.CONSTRAINT_NAME = 'FK_TRADE_DISPUTE_PREV_STATUS_CODE'
          AND k.COLUMN_NAME = 'TRD_DSP_PREV_TRD_STATUS_CD'
          AND k.REFERENCED_TABLE_SCHEMA = DATABASE()
          AND k.REFERENCED_TABLE_NAME = 'CMM_CODE' AND k.REFERENCED_COLUMN_NAME = 'CMM_CD'
          AND r.DELETE_RULE IN ('RESTRICT', 'NO ACTION')
          AND r.UPDATE_RULE IN ('RESTRICT', 'NO ACTION')
          AND (SELECT COUNT(*) FROM information_schema.KEY_COLUMN_USAGE k2
               WHERE k2.CONSTRAINT_SCHEMA = k.CONSTRAINT_SCHEMA
                 AND k2.TABLE_NAME = k.TABLE_NAME
                 AND k2.CONSTRAINT_NAME = k.CONSTRAINT_NAME) = 1
    ) AND EXISTS (
        SELECT 1
        FROM information_schema.KEY_COLUMN_USAGE k
        JOIN information_schema.REFERENTIAL_CONSTRAINTS r
          ON r.CONSTRAINT_SCHEMA = k.CONSTRAINT_SCHEMA
         AND r.CONSTRAINT_NAME = k.CONSTRAINT_NAME
         AND r.TABLE_NAME = k.TABLE_NAME
        WHERE k.CONSTRAINT_SCHEMA = DATABASE() AND k.TABLE_NAME = 'TRADE_DISPUTE'
          AND k.CONSTRAINT_NAME = 'FK_TRADE_DISPUTE_PREV_TRADE_STATUS'
          AND k.COLUMN_NAME = 'TRD_DSP_PREV_TRD_STATUS_CD'
          AND k.REFERENCED_TABLE_SCHEMA = DATABASE()
          AND k.REFERENCED_TABLE_NAME = 'CMM_CODE' AND k.REFERENCED_COLUMN_NAME = 'CMM_CD'
          AND r.DELETE_RULE IN ('RESTRICT', 'NO ACTION')
          AND r.UPDATE_RULE IN ('RESTRICT', 'NO ACTION')
          AND (SELECT COUNT(*) FROM information_schema.KEY_COLUMN_USAGE k2
               WHERE k2.CONSTRAINT_SCHEMA = k.CONSTRAINT_SCHEMA
                 AND k2.TABLE_NAME = k.TABLE_NAME
                 AND k2.CONSTRAINT_NAME = k.CONSTRAINT_NAME) = 1
    ) THEN
        ALTER TABLE TRADE_DISPUTE
            DROP FOREIGN KEY FK_TRADE_DISPUTE_PREV_STATUS_CODE;
    END IF;

    -- FK 이름은 기존 DB마다 다를 수 있으므로 이름이 아닌 단일 컬럼·참조 대상·제한 규칙을 검증한다.
    IF EXISTS (
        SELECT 1 FROM information_schema.KEY_COLUMN_USAGE
        WHERE CONSTRAINT_SCHEMA = DATABASE() AND TABLE_NAME = 'TRADE_DISPUTE'
          AND COLUMN_NAME = 'TRD_DSP_RSLT_CD' AND REFERENCED_TABLE_NAME IS NOT NULL
    ) AND NOT (
        (SELECT COUNT(DISTINCT CONSTRAINT_NAME)
         FROM information_schema.KEY_COLUMN_USAGE
         WHERE CONSTRAINT_SCHEMA = DATABASE() AND TABLE_NAME = 'TRADE_DISPUTE'
           AND COLUMN_NAME = 'TRD_DSP_RSLT_CD' AND REFERENCED_TABLE_NAME IS NOT NULL) = 1
        AND EXISTS (
            SELECT 1
            FROM information_schema.KEY_COLUMN_USAGE k
            JOIN information_schema.REFERENTIAL_CONSTRAINTS r
              ON r.CONSTRAINT_SCHEMA = k.CONSTRAINT_SCHEMA
             AND r.CONSTRAINT_NAME = k.CONSTRAINT_NAME
             AND r.TABLE_NAME = k.TABLE_NAME
            WHERE k.CONSTRAINT_SCHEMA = DATABASE() AND k.TABLE_NAME = 'TRADE_DISPUTE'
              AND k.COLUMN_NAME = 'TRD_DSP_RSLT_CD'
              AND k.REFERENCED_TABLE_SCHEMA = DATABASE()
              AND k.REFERENCED_TABLE_NAME = 'CMM_CODE' AND k.REFERENCED_COLUMN_NAME = 'CMM_CD'
              AND r.DELETE_RULE IN ('RESTRICT', 'NO ACTION')
              AND r.UPDATE_RULE IN ('RESTRICT', 'NO ACTION')
              AND (SELECT COUNT(*) FROM information_schema.KEY_COLUMN_USAGE k2
                   WHERE k2.CONSTRAINT_SCHEMA = k.CONSTRAINT_SCHEMA
                     AND k2.TABLE_NAME = k.TABLE_NAME
                     AND k2.CONSTRAINT_NAME = k.CONSTRAINT_NAME) = 1
        )
    ) THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'F-OPS-005/006 중단: 결과코드 FK 기능 계약이 다릅니다.';
    END IF;

    IF EXISTS (
        SELECT 1 FROM information_schema.KEY_COLUMN_USAGE
        WHERE CONSTRAINT_SCHEMA = DATABASE() AND TABLE_NAME = 'TRADE_DISPUTE'
          AND COLUMN_NAME = 'TRD_DSP_PROC_USR_SN' AND REFERENCED_TABLE_NAME IS NOT NULL
    ) AND NOT (
        (SELECT COUNT(DISTINCT CONSTRAINT_NAME)
         FROM information_schema.KEY_COLUMN_USAGE
         WHERE CONSTRAINT_SCHEMA = DATABASE() AND TABLE_NAME = 'TRADE_DISPUTE'
           AND COLUMN_NAME = 'TRD_DSP_PROC_USR_SN' AND REFERENCED_TABLE_NAME IS NOT NULL) = 1
        AND EXISTS (
            SELECT 1
            FROM information_schema.KEY_COLUMN_USAGE k
            JOIN information_schema.REFERENTIAL_CONSTRAINTS r
              ON r.CONSTRAINT_SCHEMA = k.CONSTRAINT_SCHEMA
             AND r.CONSTRAINT_NAME = k.CONSTRAINT_NAME
             AND r.TABLE_NAME = k.TABLE_NAME
            WHERE k.CONSTRAINT_SCHEMA = DATABASE() AND k.TABLE_NAME = 'TRADE_DISPUTE'
              AND k.COLUMN_NAME = 'TRD_DSP_PROC_USR_SN'
              AND k.REFERENCED_TABLE_SCHEMA = DATABASE()
              AND k.REFERENCED_TABLE_NAME = 'USERS' AND k.REFERENCED_COLUMN_NAME = 'USR_SN'
              AND r.DELETE_RULE IN ('RESTRICT', 'NO ACTION')
              AND r.UPDATE_RULE IN ('RESTRICT', 'NO ACTION')
              AND (SELECT COUNT(*) FROM information_schema.KEY_COLUMN_USAGE k2
                   WHERE k2.CONSTRAINT_SCHEMA = k.CONSTRAINT_SCHEMA
                     AND k2.TABLE_NAME = k.TABLE_NAME
                     AND k2.CONSTRAINT_NAME = k.CONSTRAINT_NAME) = 1
        )
    ) THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'F-OPS-005/006 중단: 처리관리자 FK 기능 계약이 다릅니다.';
    END IF;

    IF EXISTS (
        SELECT 1 FROM information_schema.KEY_COLUMN_USAGE
        WHERE CONSTRAINT_SCHEMA = DATABASE() AND TABLE_NAME = 'TRADE_DISPUTE'
          AND COLUMN_NAME = 'TRD_DSP_PREV_TRD_STATUS_CD' AND REFERENCED_TABLE_NAME IS NOT NULL
    ) AND NOT (
        (SELECT COUNT(DISTINCT CONSTRAINT_NAME)
         FROM information_schema.KEY_COLUMN_USAGE
         WHERE CONSTRAINT_SCHEMA = DATABASE() AND TABLE_NAME = 'TRADE_DISPUTE'
           AND COLUMN_NAME = 'TRD_DSP_PREV_TRD_STATUS_CD' AND REFERENCED_TABLE_NAME IS NOT NULL) = 1
        AND EXISTS (
            SELECT 1
            FROM information_schema.KEY_COLUMN_USAGE k
            JOIN information_schema.REFERENTIAL_CONSTRAINTS r
              ON r.CONSTRAINT_SCHEMA = k.CONSTRAINT_SCHEMA
             AND r.CONSTRAINT_NAME = k.CONSTRAINT_NAME
             AND r.TABLE_NAME = k.TABLE_NAME
            WHERE k.CONSTRAINT_SCHEMA = DATABASE() AND k.TABLE_NAME = 'TRADE_DISPUTE'
              AND k.COLUMN_NAME = 'TRD_DSP_PREV_TRD_STATUS_CD'
              AND k.REFERENCED_TABLE_SCHEMA = DATABASE()
              AND k.REFERENCED_TABLE_NAME = 'CMM_CODE' AND k.REFERENCED_COLUMN_NAME = 'CMM_CD'
              AND r.DELETE_RULE IN ('RESTRICT', 'NO ACTION')
              AND r.UPDATE_RULE IN ('RESTRICT', 'NO ACTION')
              AND (SELECT COUNT(*) FROM information_schema.KEY_COLUMN_USAGE k2
                   WHERE k2.CONSTRAINT_SCHEMA = k.CONSTRAINT_SCHEMA
                     AND k2.TABLE_NAME = k.TABLE_NAME
                     AND k2.CONSTRAINT_NAME = k.CONSTRAINT_NAME) = 1
        )
    ) THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'F-OPS-005/006 중단: 직전상태 FK 기능 계약이 다릅니다.';
    END IF;

    -- 새 FK를 만들어야 할 때만 정본 이름의 스키마 충돌을 사전 차단한다.
    IF (
        NOT EXISTS (
            SELECT 1 FROM information_schema.KEY_COLUMN_USAGE
            WHERE CONSTRAINT_SCHEMA = DATABASE() AND TABLE_NAME = 'TRADE_DISPUTE'
              AND COLUMN_NAME = 'TRD_DSP_RSLT_CD' AND REFERENCED_TABLE_NAME IS NOT NULL
        ) AND EXISTS (
            SELECT 1 FROM information_schema.REFERENTIAL_CONSTRAINTS
            WHERE CONSTRAINT_SCHEMA = DATABASE()
              AND CONSTRAINT_NAME = 'FK_TRADE_DISPUTE_RESULT_CODE'
        )
    ) OR (
        NOT EXISTS (
            SELECT 1 FROM information_schema.KEY_COLUMN_USAGE
            WHERE CONSTRAINT_SCHEMA = DATABASE() AND TABLE_NAME = 'TRADE_DISPUTE'
              AND COLUMN_NAME = 'TRD_DSP_PROC_USR_SN' AND REFERENCED_TABLE_NAME IS NOT NULL
        ) AND EXISTS (
            SELECT 1 FROM information_schema.REFERENTIAL_CONSTRAINTS
            WHERE CONSTRAINT_SCHEMA = DATABASE()
              AND CONSTRAINT_NAME = 'FK_TRADE_DISPUTE_PROCESSOR'
        )
    ) OR (
        NOT EXISTS (
            SELECT 1 FROM information_schema.KEY_COLUMN_USAGE
            WHERE CONSTRAINT_SCHEMA = DATABASE() AND TABLE_NAME = 'TRADE_DISPUTE'
              AND COLUMN_NAME = 'TRD_DSP_PREV_TRD_STATUS_CD' AND REFERENCED_TABLE_NAME IS NOT NULL
        ) AND EXISTS (
            SELECT 1 FROM information_schema.REFERENTIAL_CONSTRAINTS
            WHERE CONSTRAINT_SCHEMA = DATABASE()
              AND CONSTRAINT_NAME = 'FK_TRADE_DISPUTE_PREV_STATUS_CODE'
        )
    ) THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'F-OPS-005/006 중단: 새 FK 이름이 다른 테이블과 충돌합니다.';
    END IF;

    START TRANSACTION;

    INSERT INTO CMM_CODE (
        CMM_PARENT_SN, CMM_CD, CMM_NM, CMM_EXPLN, CMM_SORT_NO,
        CMM_USE_YN, CMM_REG_ID, CMM_UPDT_ID
    )
    SELECT NULL, 'TRDG06', '거래 문제 판정 결과', '관리자 거래 문제 판정 결과 코드 그룹', 420,
           'Y', 'SYSTEM', 'SYSTEM'
    WHERE NOT EXISTS (SELECT 1 FROM CMM_CODE WHERE CMM_CD = 'TRDG06');

    SELECT CMM_SN INTO v_parent_sn FROM CMM_CODE WHERE CMM_CD = 'TRDG06';

    IF EXISTS (
        SELECT 1
        FROM CMM_CODE c
        WHERE c.CMM_CD IN ('TRDC0021', 'TRDC0022', 'TRDC0023', 'TRDC0024')
          AND (NOT (c.CMM_PARENT_SN <=> v_parent_sn)
               OR (c.CMM_CD = 'TRDC0024' AND c.CMM_USE_YN <> 'N')
               OR (c.CMM_CD <> 'TRDC0024' AND c.CMM_USE_YN <> 'Y'))
    ) THEN
        ROLLBACK;
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'F-OPS-005/006 중단: 기존 TRDC0021~0024 계약이 충돌합니다.';
    END IF;

    INSERT INTO CMM_CODE (
        CMM_PARENT_SN, CMM_CD, CMM_NM, CMM_EXPLN, CMM_SORT_NO,
        CMM_USE_YN, CMM_REG_ID, CMM_UPDT_ID
    )
    SELECT v_parent_sn, 'TRDC0021', '처리 완료', '직전 거래 상태 복구 및 정산 재개', 10,
           'Y', 'SYSTEM', 'SYSTEM'
    WHERE NOT EXISTS (SELECT 1 FROM CMM_CODE WHERE CMM_CD = 'TRDC0021');

    INSERT INTO CMM_CODE (
        CMM_PARENT_SN, CMM_CD, CMM_NM, CMM_EXPLN, CMM_SORT_NO,
        CMM_USE_YN, CMM_REG_ID, CMM_UPDT_ID
    )
    SELECT v_parent_sn, 'TRDC0022', '전액 환불', '거래 취소 및 보관금 전액 환불', 20,
           'Y', 'SYSTEM', 'SYSTEM'
    WHERE NOT EXISTS (SELECT 1 FROM CMM_CODE WHERE CMM_CD = 'TRDC0022');

    INSERT INTO CMM_CODE (
        CMM_PARENT_SN, CMM_CD, CMM_NM, CMM_EXPLN, CMM_SORT_NO,
        CMM_USE_YN, CMM_REG_ID, CMM_UPDT_ID
    )
    SELECT v_parent_sn, 'TRDC0023', '정산 보류', '분쟁 처리중 및 거래·정산 보류 유지', 30,
           'Y', 'SYSTEM', 'SYSTEM'
    WHERE NOT EXISTS (SELECT 1 FROM CMM_CODE WHERE CMM_CD = 'TRDC0023');

    INSERT INTO CMM_CODE (
        CMM_PARENT_SN, CMM_CD, CMM_NM, CMM_EXPLN, CMM_SORT_NO,
        CMM_USE_YN, CMM_REG_ID, CMM_UPDT_ID
    )
    SELECT v_parent_sn, 'TRDC0024', '관리자 종결', '보관금 귀속 정책 확정 후 사용', 40,
           'N', 'SYSTEM', 'SYSTEM'
    WHERE NOT EXISTS (SELECT 1 FROM CMM_CODE WHERE CMM_CD = 'TRDC0024');

    SELECT CMM_SN INTO v_parent_sn FROM CMM_CODE WHERE CMM_CD = 'STLG01';

    IF EXISTS (
        SELECT 1 FROM CMM_CODE
        WHERE CMM_CD = 'STLC0004'
          AND (NOT (CMM_PARENT_SN <=> v_parent_sn) OR CMM_USE_YN <> 'Y')
    ) THEN
        ROLLBACK;
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'F-OPS-005/006 중단: 기존 STLC0004 계약이 충돌합니다.';
    END IF;

    INSERT INTO CMM_CODE (
        CMM_PARENT_SN, CMM_CD, CMM_NM, CMM_EXPLN, CMM_SORT_NO,
        CMM_USE_YN, CMM_REG_ID, CMM_UPDT_ID
    )
    SELECT v_parent_sn, 'STLC0004', '환불종결', '전액 환불로 종료된 정산', 40,
           'Y', 'SYSTEM', 'SYSTEM'
    WHERE NOT EXISTS (SELECT 1 FROM CMM_CODE WHERE CMM_CD = 'STLC0004');

    COMMIT;

    -- 기존 행을 보존하기 위해 신규 컬럼은 모두 NULL 허용으로 추가한다.
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.COLUMNS
        WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'TRADE_DISPUTE'
          AND COLUMN_NAME = 'TRD_DSP_RSLT_CD'
    ) THEN
        ALTER TABLE TRADE_DISPUTE
            ADD COLUMN TRD_DSP_RSLT_CD VARCHAR(30) NULL
                COMMENT '거래분쟁판정결과공통코드(TRDG06)' AFTER TRD_DSP_STATUS_CD;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM information_schema.COLUMNS
        WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'TRADE_DISPUTE'
          AND COLUMN_NAME = 'TRD_DSP_PREV_TRD_STATUS_CD'
    ) THEN
        ALTER TABLE TRADE_DISPUTE
            ADD COLUMN TRD_DSP_PREV_TRD_STATUS_CD VARCHAR(30) NULL
                COMMENT '분쟁접수직전거래상태공통코드(TRDG02)' AFTER TRD_DSP_RSLT_CD;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM information_schema.COLUMNS
        WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'TRADE_DISPUTE'
          AND COLUMN_NAME = 'TRD_DSP_PROC_RSN_CN'
    ) THEN
        ALTER TABLE TRADE_DISPUTE
            ADD COLUMN TRD_DSP_PROC_RSN_CN VARCHAR(4000) NULL
                COMMENT '관리자판정처리사유내용' AFTER TRD_DSP_CN;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM information_schema.COLUMNS
        WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'TRADE_DISPUTE'
          AND COLUMN_NAME = 'TRD_DSP_PROC_USR_SN'
    ) THEN
        ALTER TABLE TRADE_DISPUTE
            ADD COLUMN TRD_DSP_PROC_USR_SN BIGINT NULL
                COMMENT '처리관리자회원일련번호' AFTER TRD_DSP_PROC_RSN_CN;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM information_schema.COLUMNS
        WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'TRADE_DISPUTE'
          AND COLUMN_NAME = 'TRD_DSP_PROC_DT'
    ) THEN
        ALTER TABLE TRADE_DISPUTE
            ADD COLUMN TRD_DSP_PROC_DT DATETIME NULL
                COMMENT '관리자판정처리일시' AFTER TRD_DSP_PROC_USR_SN;
    END IF;

    -- 직전 상태는 접수 시각보다 엄격히 이전인 전체 상태이력 중 최신 1건을 먼저 고른다.
    -- 그 최신 행 자체가 TRDG02 소속이며 복구 가능한 0003/0004/0005일 때만 확정한다.
    DROP TEMPORARY TABLE IF EXISTS TMP_F_OPS_005_006_PREV_STATUS;
    CREATE TEMPORARY TABLE TMP_F_OPS_005_006_PREV_STATUS AS
    SELECT TRD_DSP_SN, TRD_STS_HST_STATUS_CD
    FROM (
        SELECT d.TRD_DSP_SN,
               h.TRD_STS_HST_STATUS_CD,
               ROW_NUMBER() OVER (
                   PARTITION BY d.TRD_DSP_SN
                   ORDER BY h.TRD_STS_HST_REG_DT DESC, h.TRD_STS_HST_SN DESC
               ) AS rn
        FROM TRADE_DISPUTE d
        JOIN TRADE_STATUS_HIST h
          ON h.TRD_SN = d.TRD_SN
         AND h.TRD_STS_HST_REG_DT < d.TRD_DSP_REG_DT
        WHERE d.TRD_DSP_PREV_TRD_STATUS_CD IS NULL
    ) ranked
    JOIN CMM_CODE status_code
      ON status_code.CMM_CD = ranked.TRD_STS_HST_STATUS_CD
    JOIN CMM_CODE status_group
      ON status_group.CMM_SN = status_code.CMM_PARENT_SN
     AND status_group.CMM_CD = 'TRDG02'
    WHERE ranked.rn = 1
      AND ranked.TRD_STS_HST_STATUS_CD IN ('TRDC0003', 'TRDC0004', 'TRDC0005');

    UPDATE TRADE_DISPUTE d
    JOIN TMP_F_OPS_005_006_PREV_STATUS p ON p.TRD_DSP_SN = d.TRD_DSP_SN
    SET d.TRD_DSP_PREV_TRD_STATUS_CD = p.TRD_STS_HST_STATUS_CD
    WHERE d.TRD_DSP_PREV_TRD_STATUS_CD IS NULL;

    SET v_backfilled_count = ROW_COUNT();
    DROP TEMPORARY TABLE TMP_F_OPS_005_006_PREV_STATUS;

    IF NOT EXISTS (
        SELECT 1 FROM information_schema.STATISTICS
        WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'TRADE_DISPUTE'
          AND SEQ_IN_INDEX = 1 AND COLUMN_NAME = 'TRD_DSP_RSLT_CD'
    ) THEN
        ALTER TABLE TRADE_DISPUTE
            ADD KEY IDX_TRADE_DISPUTE_RESULT (TRD_DSP_RSLT_CD);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM information_schema.STATISTICS
        WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'TRADE_DISPUTE'
          AND SEQ_IN_INDEX = 1 AND COLUMN_NAME = 'TRD_DSP_PROC_USR_SN'
    ) THEN
        ALTER TABLE TRADE_DISPUTE
            ADD KEY IDX_TRADE_DISPUTE_PROC_USR (TRD_DSP_PROC_USR_SN);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM information_schema.STATISTICS
        WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'TRADE_DISPUTE'
          AND SEQ_IN_INDEX = 1 AND COLUMN_NAME = 'TRD_DSP_PREV_TRD_STATUS_CD'
    ) THEN
        ALTER TABLE TRADE_DISPUTE
            ADD KEY IDX_TRADE_DISPUTE_PREV_STATUS (TRD_DSP_PREV_TRD_STATUS_CD);
    END IF;

    IF EXISTS (
        SELECT 1 FROM information_schema.KEY_COLUMN_USAGE
        WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'TRADE_DISPUTE'
          AND COLUMN_NAME = 'TRD_DSP_RSLT_CD' AND REFERENCED_TABLE_NAME IS NOT NULL
    ) AND NOT EXISTS (
        SELECT 1 FROM information_schema.KEY_COLUMN_USAGE
        WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'TRADE_DISPUTE'
          AND COLUMN_NAME = 'TRD_DSP_RSLT_CD'
          AND REFERENCED_TABLE_SCHEMA = DATABASE()
          AND REFERENCED_TABLE_NAME = 'CMM_CODE' AND REFERENCED_COLUMN_NAME = 'CMM_CD'
    ) THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'F-OPS-005/006 중단: TRD_DSP_RSLT_CD FK 대상이 다릅니다.';
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM information_schema.KEY_COLUMN_USAGE
        WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'TRADE_DISPUTE'
          AND COLUMN_NAME = 'TRD_DSP_RSLT_CD' AND REFERENCED_TABLE_NAME IS NOT NULL
    ) THEN
        ALTER TABLE TRADE_DISPUTE
            ADD CONSTRAINT FK_TRADE_DISPUTE_RESULT_CODE
            FOREIGN KEY (TRD_DSP_RSLT_CD) REFERENCES CMM_CODE (CMM_CD)
            ON DELETE RESTRICT ON UPDATE RESTRICT;
    END IF;

    IF EXISTS (
        SELECT 1 FROM information_schema.KEY_COLUMN_USAGE
        WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'TRADE_DISPUTE'
          AND COLUMN_NAME = 'TRD_DSP_PROC_USR_SN' AND REFERENCED_TABLE_NAME IS NOT NULL
    ) AND NOT EXISTS (
        SELECT 1 FROM information_schema.KEY_COLUMN_USAGE
        WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'TRADE_DISPUTE'
          AND COLUMN_NAME = 'TRD_DSP_PROC_USR_SN'
          AND REFERENCED_TABLE_SCHEMA = DATABASE()
          AND REFERENCED_TABLE_NAME = 'USERS' AND REFERENCED_COLUMN_NAME = 'USR_SN'
    ) THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'F-OPS-005/006 중단: TRD_DSP_PROC_USR_SN FK 대상이 다릅니다.';
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM information_schema.KEY_COLUMN_USAGE
        WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'TRADE_DISPUTE'
          AND COLUMN_NAME = 'TRD_DSP_PROC_USR_SN' AND REFERENCED_TABLE_NAME IS NOT NULL
    ) THEN
        ALTER TABLE TRADE_DISPUTE
            ADD CONSTRAINT FK_TRADE_DISPUTE_PROCESSOR
            FOREIGN KEY (TRD_DSP_PROC_USR_SN) REFERENCES USERS (USR_SN)
            ON DELETE RESTRICT ON UPDATE RESTRICT;
    END IF;

    IF EXISTS (
        SELECT 1 FROM information_schema.KEY_COLUMN_USAGE
        WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'TRADE_DISPUTE'
          AND COLUMN_NAME = 'TRD_DSP_PREV_TRD_STATUS_CD' AND REFERENCED_TABLE_NAME IS NOT NULL
    ) AND NOT EXISTS (
        SELECT 1 FROM information_schema.KEY_COLUMN_USAGE
        WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'TRADE_DISPUTE'
          AND COLUMN_NAME = 'TRD_DSP_PREV_TRD_STATUS_CD'
          AND REFERENCED_TABLE_SCHEMA = DATABASE()
          AND REFERENCED_TABLE_NAME = 'CMM_CODE' AND REFERENCED_COLUMN_NAME = 'CMM_CD'
    ) THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'F-OPS-005/006 중단: TRD_DSP_PREV_TRD_STATUS_CD FK 대상이 다릅니다.';
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM information_schema.KEY_COLUMN_USAGE
        WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'TRADE_DISPUTE'
          AND COLUMN_NAME = 'TRD_DSP_PREV_TRD_STATUS_CD' AND REFERENCED_TABLE_NAME IS NOT NULL
    ) THEN
        ALTER TABLE TRADE_DISPUTE
            ADD CONSTRAINT FK_TRADE_DISPUTE_PREV_STATUS_CODE
            FOREIGN KEY (TRD_DSP_PREV_TRD_STATUS_CD) REFERENCES CMM_CODE (CMM_CD)
            ON DELETE RESTRICT ON UPDATE RESTRICT;
    END IF;

    SELECT v_backfilled_count AS backfilled_previous_trade_status_count;
END $$

CALL SP_F_OPS_005_006_APPLY_DISPUTE_DB() $$
DROP PROCEDURE SP_F_OPS_005_006_APPLY_DISPUTE_DB $$

DELIMITER ;
